### ISSUE TITLE
Not usable in RN

### ISSUE THREAD

**Issue by slorber** [faaez/creditcardutils#4]
This code relies on dom events so it's not usable in RN. See for example formatCardNumber

**Comment by evanjmg** [comment]
It works fine for me in RN. just call the function on every textChange event

**Comment by ansal-exp** [comment]
Nope, it's not working with RN. I will add some specific details which will help someone.

As per documentation, formatCardNumber method will restrict the card number length to 16, it's not working.
As per documentation, formatCardNumber method will restrict the input to numbers, it's not working. 
validateCardNumber method is returning true even if the input length (formatted input) greater than 20 :-(
